alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias :q='exit'
alias cls='clear'
alias al='cd C:/Users/rajpr/AppData/Local'
alias ws='cd C:/Users/rajpr/Workspace/'
